# Generated by Django 4.2.2 on 2023-06-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmployeesDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("emp_name", models.CharField(max_length=50, unique=True)),
                ("emp_city", models.CharField(max_length=50)),
                ("emp_state", models.CharField(max_length=50)),
                ("emp_designation", models.CharField(max_length=50)),
                ("emp_date_of_joinning", models.DateField()),
                ("emp_status", models.CharField(max_length=50)),
                ("emp_salary", models.CharField(max_length=50)),
            ],
        ),
    ]
